# Los archivos docker-compose.yml son versionados, lo que significa que es muy importante indicar la versión de las instrucciones que queremos darle.
version: "3.3"

# Servidor nginx
services:
  web:
    # versión
    image: nginx:latest
    # Puerto 8080
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  # Configuración de php-fpm
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./src:/var/www/html
    links:
      - db
  db:
      image: mysql
      ports:
        - "3307:3306"
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: dbname
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
      volumes:
        - ./dump:/docker-entrypoint-initdb.d
        - ./conf:/etc/mysql/conf.d
        - persistent:/var/lib/mysql
      networks:
        - default
  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
          - db:db
        ports:
          - 8081:80
        environment:
          MYSQL_USER: root
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test
volumes:
  persistent:
